[package]
name = "rust-tak"
version = "0.1.1"
authors = ["Justin Kur <JustinK97@hotmail.com>"]

[dependencies]
ndarray = "0.10.0"
regex = "0.2"
lazy_static = "0.2"

[dev-dependencies]
sqlite = "0.23.9"